The ``7-base_geometry`` module
======================

Using ``integer_validator``
-------------------
This is a doctest based on 7-base_geometry.py
Each '>>>' line is run as if in a python shell, and counts as a test.
The next line, if not '>>>' is the expected output of the previous line.
If anything doesn't match exactly (including trailing spaces), the test fails.

Test 0: import function:
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Test 1: exception requested by task
>>> bg = BaseGeometry()
>>> bg.area()
Traceback (most recent call last):
    ...
Exception: area() is not implemented


Test 2: passing one str and one int (correct output)
>>> bg = BaseGeometry()
>>> bg.integer_validator("name", 10)

Test 3: no arguments passed
>>> bg = BaseGeometry()
>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test 4: passing two strings
>>> bg = BaseGeometry()
>>> bg.integer_validator("name", "same")
Traceback (most recent call last):
...
TypeError: name must be an integer

Test 5: passing two integers
>>> bg = BaseGeometry()
>>> bg.integer_validator(10, 12)

Test 6: empty string
>>> bg = BaseGeometry()
>>> bg.integer_validator("", 12)

Test 7: passing None
>>> bg = BaseGeometry()
>>> bg.integer_validator(None, None)
Traceback (most recent call last):
...
TypeError: None must be an integer

Test 8: passing a negative integer
>>> bg = BaseGeometry()
>>> bg.integer_validator("name", -1)
Traceback (most recent call last):
...
ValueError: name must be greater than 0

Test 9: passing a 0
>>> bg = BaseGeometry()
>>> bg.integer_validator("name", 0)
Traceback (most recent call last):
...
ValueError: name must be greater than 0

Test 10: with one argument str
>>> bg = BaseGeometry()
>>> bg.integer_validator("name")
Traceback (most recent call last):
    ...
TypeError: integer_validator() missing 1 required positional argument: 'value'

Test 11: only one argument int
>>> bg = BaseGeometry()
>>> bg.integer_validator(20)
Traceback (most recent call last):
    ...
TypeError: integer_validator() missing 1 required positional argument: 'value'
